### ISSUE TITLE
Navigatie volgorde beheren

### ISSUE THREAD

**Issue by bddjong** [frameless/strapi#361]
Het is niet meteen duidelijk hoe de volgorde van het hoofdmenu wordt opgebouwd en dat wringt een beetje bij de BA's:
we maken het mogelijk dat redactie zelf kiest waaruit het hoofdmenu bestaat. 

Zo kan zelf de volgorde worden bepaald en worden gezorgd dat niet alle hoofditems erin staan.

**Comment by Robbert** [comment]
Code voor sorteren van main navigation items:

https://github.com/frameless/strapi/blob/main/apps/vth-frontend/src/app/%5Blocale%5D/layout.tsx#L74-L78

Voorbeeldcode voor sorteren op basis van een `order` property.

```js
[...arr].sort((a, b) => {
  if (typeof a.order !== 'number' || typeof b.order !== 'number')
  return 0; return a > b ? 1 : -1;
})
```
