### ISSUE TITLE
CSP environment variables

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#409]
Het DevOps team moet per omgeving kunnen configureren naar welke URLs verbinding gemaakt mag worden, zodat de embbedded form gegevens naar de OpenForms API kan verzenden.

We kunnen een of meerdere CSP variabelen uitlezen om die verbinding toe te staan. Bijvoorbeeld

`.acc.env`:

```
CSP_CONNECT_SRC="https://acc.openforms.example.com/"
```

Zodat de header wordt:

```
Content-Security-Policy: ....; connect-src 'self' https://acc.openforms.example.com/; ...
```

- [x] Environment uitlezen, header instellen
- [x] Environment variable escapen, zodat niet andere policies aangepast kunnen worden
- [x] README updaten met documentatie over header

**Comment by bddjong** [comment]
Implementation for now only takes very specific endpoint configuration and not generic configuration for CSP attributes such as `connect-src: {env}`. I don't see a reason to open up the configuration to endpoints that are not intended features to be included.
