### ISSUE TITLE
Backend CORS configuration

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#414]
To enable embedding the Open Forms SDK on domains other than the domain where the backend is deployed, you need to appropriately [configure](https://open-forms.readthedocs.io/en/stable/installation/config.html#installation-environment-config) a number of settings.

By default Open Forms will not allow requests from Strapi CMS to Open Forms. [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) HTTP headers on the Open Forms server must mention the hostname of the Strapi CMS, so the browser will no longer block the requests.

A correct CORS header will look something like this.

```http
Access-Control-Allow-Origin: http://strapi-cms.utrecht.nl
```

The server should respond with the above header if the request is made from `Origin: http://strapi-cms.utrecht.nl`, and otherwise not  send this header at all.

The following would also work, but allowing anything would be bad for security:

```http
Access-Control-Allow-Origin: *
```

https://open-forms.readthedocs.io/en/stable/developers/sdk/embedding.html#backend-configuration

**Comment by bddjong** [comment]
This is now successfully configured on `ont` by the ops team
