### ISSUE TITLE
Strapi ➝ Open Forms configured in ontw environment

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#422]
This work is mostly in the hands of Utrecht devops. 
- [x] Strapi network needs to be able to connect to open forms
- [x] Strapi needs the `OPEN_FORMS_API_URL` environment variable configured

This issue is closely tied to #414

**Comment by bddjong** [comment]
Verzoek is ingediend bij devops

**Comment by bddjong** [comment]
Ik heb al een PR geopend en gemerged voor de `OPEN_FORMS_API_URL`. Voor de `-API_TOKEN` wachten we nog tot deze in de vault gezet wordt
