### ISSUE TITLE
Strapi ➝ Open Forms configured in acc environment

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#423]
*For us:*
- [x] `OPEN_FORMS_API_URL` configured for acc through tenant repo for both pdc frontend and strapi backend applications, test environment has already been configured (@AliKdhim87 or @bddjong know where to find this)

*For devops*
- [x] `OPEN_FORMS_API_TOKEN` needs to be added to secret vault for acc 
- [x] Open Forms in acc needs its CORS configured to allow requests from both the pdc cms and pdc frontend

**Comment by AliKdhim87** [comment]
![Image](https://github.com/frameless/strapi/assets/53454241/8642783b-9055-4b36-be70-c2d1b92ee107)
