### ISSUE TITLE
Formulier tonen in Digitaal Loket

### ISSUE THREAD

**Issue by Yolijn** [frameless/strapi#427]
- [x] NextJS route voor `formulier/:slug`
- [x] Pagina bevat React component voor OpenFormsEmbed #418 
- [ ] Header en footer kunnen in overleg met René en Jeroen anders zijn dan normale product pagina's

**Comment by bddjong** [comment]
De nextjs route en gebruik van OpenFormsEmbed zitten al in #405. Voor de route is er nog werk nodig:
-  form-step routing ondersteunen (`/form/:slug/form-step` gaat bij refresh kapot. Catch-all route nodig vanaf `:slug` om door te voeren naar open formulieren)
- Refresh gaat kapot (waarschijnlijk dezelfde fix als bovenstaande issue)
