### ISSUE TITLE
Design system styling voor Open forms rich text component

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#430]
Ik herinner me dat in Open Forms is het mogelijk is om rich-text toe te voegen. Bijvoorbeeld een lapje tekst met een tabelletje, wat linkjes en een bullet list.

De design tokens van het design system moeten hierop ingesteld zijn, zodat het er goed uit ziet.

Mogelijk moet er een `class="utrecht-html"` omheen om dit te bereiken, dan gaan veel dingen al goed.

We moeten ook ontdekken welke dingen mogelijk zijn in de rich text component, die dan nog niet goed gaan.

```html
<div class="utrecht-html" style="--utrecht-space-around: 1">
   {intro pagina}
</div>
```

👆 maybe?

---

Acceptatie criteria:

een intro pagina gemaakt in Strapi is niet te onderscheiden van een intro pagina gemaakt in Open Forms.

**Comment by scar055** [comment]
Rich text component is denk ik de free text in open forms docker. Die gebruikt de content component om de text te maken en gebruikt dus niet utrecht componenten maar gewoon html.

**Comment by scar055** [comment]
pull request: https://github.com/frameless/open-forms-sdk/pull/2
