### ISSUE TITLE
Radio buttons kan je unchecken

### ISSUE THREAD

**Issue by scar055** [frameless/strapi#441]
De open form radio buttons kan je unchecken zoals een checkbox

**Comment by Robbert** [comment]
@scar055 Is dit alleen [in Storybook](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/open-forms-radio--docs), of valt dit reproduceren in Open Forms?

**Comment by scar055** [comment]
> [@scar055](https://github.com/scar055) Is dit alleen [in Storybook](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/open-forms-radio--docs), of valt dit reproduceren in Open Forms?

ja dit is ook bij open forms

**Comment by Robbert** [comment]
Proof: https://open-formulieren.github.io/open-forms-sdk/?path=/story/form-io-components-vanilla-radio--radio

Zou een issue aanmaken bij open forms

**Comment by scar055** [comment]
dit is een component dat door formio is gemaakt en daar kan je het ook unchecken dus ik denk niet dat deze issue gefixed kan worden.
