### ISSUE TITLE
Select lijst is niet goed te zien

### ISSUE THREAD

**Issue by scar055** [frameless/strapi#442]
Open forms: select lijst als je die open klapt kan je de opties niet zien

**Comment by Robbert** [comment]
Is deze al gefixt (na de upgrade naar sdk 2.2.0 wellicht?
Dit ziet er goed uit: https://nl-design-system.github.io/utrecht/storybook/?path=/docs/open-forms-select--docs

**Comment by Robbert** [comment]
Fixed by update, jay!
