### ISSUE TITLE
Intro-pagina van een formulier

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#457]
Uitzoeken: hoe wordt de intro-pagina gemaakt? Is dat in Strapi, of in Open Forms?

Vijay weet dit waarschijnlijk.

**Antwoord op de vraag boven:**

intro pagina wordt gemaakt in open forms.
als je een form aanmaakt moet je een title mee geven dus dan heb je al de front page.
front page kan je in 2 talen maken Nederlands en Engels.
Title van de front page kan niet leeg.

De form bij hun preview wordt direct dus een intro pagina, een form en jouw resultaten pagina mee gegeven.

zie deze issue voor[ intro pagina ](https://github.com/orgs/frameless/projects/27/views/1?pane=issue&itemId=53700917)voorbeeld screen shot

![Image](https://github.com/frameless/strapi/assets/48519289/b8dfea83-ead2-4bdc-b315-3db53159996e)

**Comment by Robbert** [comment]
@scar055 Even aan Vijay vragen om de meest complexe voorbeelden van intro-pagina's (in de #utrecht-design-system-kernteam channel)

- [ ] voorbeeld inladen van compelxe intro pagina
- [ ] make it look good, als het veel werk is even losse issues aanmaken

**Comment by scar055** [comment]
Introductie pagina zit in de slug van de forms.
De form collection gaat weg volgens @bddjong dus ik denk niet dat ik verder iets hoef te doen zie [slack](https://almost-frameless.slack.com/archives/C06GRPLS0AY/p1708594289144609) voor meer uitleg
