### ISSUE TITLE
Add Google Maps to CSP

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#471]
https://developers.google.com/maps/documentation/javascript/content-security-policy

Neem de voorbeeld CSP niet klakkeloos over;

- `https:` is waarschijnlijk _overly broad_
- prefix alle domeinen met `https://`, doe niet zomaar `*.google.com`
- als het dan niet werkt, let @Robbert know

**Comment by Robbert** [comment]
@bddjong Wil jij de CSP reviewen?

**Comment by scar055** [comment]
https://github.com/frameless/strapi/pull/478
