### ISSUE TITLE
Onderzoek naar gebruik van zowel punt als komma in numeriek veld voor kosten => Gebruikerstest

### ISSUE THREAD

**Issue by AliKdhim87** [frameless/strapi#480]
**Beschrijving:**
We moeten onderzoeken of het mogelijk is om zowel een punt als een komma te gebruiken in een numeriek veld voor de kosten. Momenteel wordt op de editor een komma gebruikt, terwijl op de frontend een punt wordt gebruikt. We moeten nagaan of deze flexibiliteit behouden kan blijven bij de volgende update.

**Screeshouts**

- Kostenveld op het Strapi-dashboard
   > **Notitie**: Ik heb het veld zelf getest en het werkt wel

    ![Image](https://github.com/frameless/strapi/assets/53454241/419ca851-8032-47a0-af7f-fba13c6417cb)

 - Richtext field:
    ![Image](https://github.com/frameless/strapi/assets/53454241/e6c595cf-7452-492b-825c-73e8122a23dd)

- Op de frontend 
  ![Image](https://github.com/frameless/strapi/assets/53454241/a00d88fc-ea48-4896-9a15-1c37570f88b1)

**Comment by Robbert** [comment]
@AliKdhim87 Verandert het Strapi veld van een punt naar een komma als je wisselt van Engels naar Nederlands?

Dan is dit denk ik niet iets om "op te lossen", dit is gewoon onderdeel van "localisatie".

**Comment by AliKdhim87** [comment]
@Robbert , Ja het is inderdaad door de localisatie.
