### ISSUE TITLE
Voeg table heading cells toe in de accordeon

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#490]
**Beschrijving:**

De [VTH in cijfers pagina](https://vth-programma-verslag.digitaal.utrecht.nl/nl/vth-in-cijfers#main) heeft in accordion met Tables binnen. 
Momenteel zijn wat Table Headers zullen zijn alleen met Bold gestyled om ze te onderscheiden met de andere rijen van de Tables.

<img width="1400" alt="Table zonder een header" src="https://github.com/frameless/strapi/assets/11764984/1493fa1c-dee5-4721-bf21-c6a9806823b0">

Deze Tables hebben geen Table Headers, waardoor de inhoud van de Tabellen niet toegankelijk is.

**Oplossing:** Zet de eerste rij van elk Table in een Table Head element (vanuit de Table body te halen)

**Zie** [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead)

**WCAG Succes Criteria:**
1.3.1
4.1.2

**Comment by AliKdhim87** [comment]
Ik denk dat dit probleem kan worden opgelost via het VTH-dashboard door de inhoud aan te passen en de header toe te voegen.

**Comment by Robbert** [comment]
Als de volgende twee issues zijn opgelost, dan zou het probleem voor nieuwe tabellen hopelijk niet meer voorkomen:

- https://github.com/frameless/strapi/issues/742
- https://github.com/frameless/strapi/issues/741

Voor de huidige tabellen moeten de redacteuren zelf nog aanpassingen doen, door bijvoorbeeld de tabellen opnieuw aan te maken.
