### ISSUE TITLE
Fix buiten beeld Navigatie item wanneer ingezoomd

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#491]
**Beschrijving:** De [Parkeergarages pagina](https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/parkeergarages) in Zoom Text Only mode in Firefox met een Zoom groter than 200% maakt de laatste item van navigatie buiten beeld.
<img width="1444" alt="web pagina navigatie waar de laatste item niet zichtbar is" src="https://github.com/frameless/strapi/assets/11764984/05c8f954-0842-4315-b41b-6a04e4f06862">

**Oplossing:**  Wordt Onderzocht. Suggesties zijn welkom.

**Comment by scar055** [comment]
volgens mij is dit al gefixed want als ik inzoom tot 200% komt er een burger menu dus ik denk dat de redactie nog iets moeten updaten.

**Comment by bddjong** [comment]
Ook PDC checken of dit een probleem is

**Comment by savitris** [comment]
> volgens mij is dit al gefixed want als ik inzoom tot 200% komt er een burger menu dus ik denk dat de redactie nog iets moeten updaten.

@scar055 
Helaas als je inzoom tot 200% in Zoom text only mode in Firefox komt er geen burger menu bij de VTH site. **Zelfs om 500% zoom komt er geen burger menu.**

De PDC Navigation heeft hetzelfde issue

-
VTH site
200% zoom
Firefox Zoom Text only
![Image](https://github.com/frameless/strapi/assets/11764984/b9f0541a-3ce0-450d-951b-426f93a03704)

-
VTH site
500% zoom
Firefox Zoom Text only
![Image](https://github.com/frameless/strapi/assets/11764984/57af2c26-ca56-46e2-88de-7afaa12bdc1b)


-
PDC site
200% zoom
Firefox Zoom Text only
![Image](https://github.com/frameless/strapi/assets/11764984/2fcea036-106f-4e93-976d-8a932a2e8387)

-
PDC site
500% zoom
Firefox Zoom Text only
![Image](https://github.com/frameless/strapi/assets/11764984/5299d727-0205-406d-9759-6435fdf91a95)
