### ISSUE TITLE
Fix tekst in Accordion die overstroomt als man ingezoomd is

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#492]
**Beschrijving:** Als man in de [VTH in cijfers pagina](https://vth-programma-verslag.digitaal.utrecht.nl/nl/vth-in-cijfers#main) 400% zoom of meer is ingezoomd, is de tekst binnen de Accordion aan het overstromen.

<img width="1408" alt="tabel valt uit het beeld wanneer ingezoomd" src="https://github.com/frameless/strapi/assets/11764984/61eb1b7e-7f1b-43c3-8470-12ad3622c45f">

**Comment by scar055** [comment]
volgens mij moet het VTH ook dit nog updaten want als ik het in de development na maakt en naar 400% inzoomed dan valt het niet uit de accordion
