### ISSUE TITLE
fix niet zichtbar Side Navigation wanneer ingezoomd

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#495]
**Beschrijving:**  De Side Navigation (.utrecht-sidenav) van de [Parkeergarages pagina ](https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/parkeergarages ) met Links naar andere paginas is niet zichtbaar wanneer man 150% of meer ingezoomd is.

**Zoom 100%**
<img width="1204" alt="Screenshot 2024-03-11 at 16 27 43" src="https://github.com/frameless/strapi/assets/11764984/9d20ebee-bd6c-4e38-bfff-b491d0428d25">

**Zoom 150%**
<img width="1164" alt="Screenshot 2024-03-11 at 16 28 04" src="https://github.com/frameless/strapi/assets/11764984/dc7d1839-0748-4f31-aa15-339ed4d6b06e">

**WCAG Succes Criteria:**
1.4.4
1.4.10
2.4.1
2.4.5

**Comment by scar055** [comment]
is de side navagation dan nog met een side scroll of de tab focus te zien op de pagina zelf? of is het dat de side navagation gewoon weg is?

**Comment by savitris** [comment]
> is de side navagation dan nog met een side scroll of de tab focus te zien op de pagina zelf? of is het dat de side navagation gewoon weg is?

De Side Navigation-component verdwijnt volledig en is niet te bereiken wanneer er wordt ingezoomd.
