### ISSUE TITLE
fix glijdende social media icons voor styling en contrast

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#499]
**Beschrijving:** Momenteel in de [Parkeergarages pagina](https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/parkeergarages) in de zoom Only text mode, wanneer man inzoom, worden de social media icons uitgeglijd van hun richtige plek.
Dit is niet goed voor de design, en ook voor de contrast tussen het wit van de icons en het rood van de achtergrond.
Als de iconen buiten hun cirkel staan, is de contrast alleen passend omdat ze grafieken zijn.

**Zoom 100%**
<img width="254" alt="social media icons" src="https://github.com/frameless/strapi/assets/11764984/d0965f86-68fd-4f09-aa0d-21a9f31154ea">
**Zoom 120%**
<img width="256" alt="social media icons shifted downwards" src="https://github.com/frameless/strapi/assets/11764984/62ce0572-33ae-4b97-82a7-e2588009e1e5">
**Zoom 150%**
<img width="254" alt="social media icons shifted downwards even more" src="https://github.com/frameless/strapi/assets/11764984/f7e2f6e9-8e7c-4bbc-bef6-09dfaeb7a85e">
**Zoom 200%**
<img width="266" alt="social media icons shifted downwards so much some of them are fully out of their respective designated containers" src="https://github.com/frameless/strapi/assets/11764984/570a6d67-fb64-4497-a5bd-d8516d81f65c">
**Oplossing:**  .utrecht-link-social zet line-height to 1 maakt het goed. De icons hebben een line-height van 60 een de achtergrond cirkel heeft een max height van 40px, dit maakt dat de icon beelden naar beneden glijden.

**Comment by AliKdhim87** [comment]
Deze probleem is opgelost na de bijwerkingen van de productieomgeving
