### ISSUE TITLE
Add accessible name to tables within accordion

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#514]
**Beschrijving:**  In de [VTH in cijfers pagina ](https://vth-programma-verslag.digitaal.utrecht.nl/nl/vth-in-cijfers#main ) hebben de Tables binnen het Accordion geen toegankelijke naam.
![Developer tools capture showcasing a table without an accessible name](https://github.com/frameless/strapi/assets/11764984/695602dc-dc67-48cf-9725-669d35d14d63)

**Oplossing:**  Toevoeging van captions of arialabeledby om te verwijzen naar de titel van elk van de accordeonitems en hun respectievelijke tabellen.

**WCAG Succes Criteria:**
1.3.1
2.4.6
4.1.2

**Comment by AliKdhim87** [comment]
Deze issue kan opgelost worden door iemand van de redactie team via het Strapi-dashboard, omdat we renderen wat we vanuit Strapi ontvangen.
