### ISSUE TITLE
Menu kleinere schermen op vreemde locatie

### ISSUE THREAD

**Issue by Ollie-nl** [frameless/strapi#542]
Op productie

Als bezoeker verwacht ik, op kleine schermen zoals bijvoorbeeld mobiel, een link naar het menu rechtsboven op de pagina te vinden, zodat ik gemakkelijk kan navigeren naar andere pagina’s. 

![image](https://github.com/frameless/strapi/assets/48805670/f42713a0-2af8-4405-9496-68bdefe9636d)

**Comment by JeroenduC** [comment]
@Ollie-nl : Deze lijkt inmiddels gefixt. Of was er nog iets met de precieze locatie?

**Comment by Ollie-nl** [comment]
Menu staat nu rechts boven, later kijken naar paddings van de menu "block start" en "inline end"
