### ISSUE TITLE
Layout breadcrumb verspringt op op meerdere regels

### ISSUE THREAD

**Issue by Ollie-nl** [frameless/strapi#544]
Op productie

Als een bezoeker een pagina met een een breadcrumb over meerdere regels of klein scherm, heeft dan geeft deze een verspringende layout.

<img width="374" alt="voorbeeld van een breadcrumb" src="https://github.com/frameless/strapi/assets/48805670/991a01a9-2e36-46de-b4a3-9467dbe08e62">

Layout van breadcrumb gelijk trekken met Figma bestanden

**Comment by AliKdhim87** [comment]
Deze probleem is opgelost door de bijwerking van de productieomgeving.
