### ISSUE TITLE
Integreer de Pandosearch-URL van Utrecht in de PDC in plaats van de Pndoshearch ontwikkelings-URL.

### ISSUE THREAD

**Issue by AliKdhim87** [frameless/strapi#562]
**Beschrijving:**

Op dit moment maken we gebruik van de PandoSearch-ontwikkelings-URL, een demo-URL die reageert met PandoSearch-gegevens in plaats van die van Utrecht.

**Comment by Robbert** [comment]
We moeten pandosearch een mailtje sturen als de site live is.
