### ISSUE TITLE
CTA op smalle container

### ISSUE THREAD

**Issue by Ollie-nl** [frameless/strapi#583]
Als een bezoeker de pagina opent op een kleiner scherm komen er grijze verticale lijnen op de buttons heen, deze mogen weg voor een smalle container zodat het nettere weergave geeft.

![image](https://github.com/frameless/strapi/assets/48805670/4db8b8b0-d420-4698-b906-6622c6601d18)

https://loket.digitaal.utrecht.nl/nl/products/planschade-schadevergoeding-aanvragen

**Comment by Yolijn** [comment]
Issue is opgelost
