### ISSUE TITLE
Oekraiens toevoegen aan mogelijke talen

### ISSUE THREAD

**Issue by JeroenduC** [frameless/strapi#591]
We willen graag de Oekraiense taal kunnen toevoegen aan een stuk tekst in een content blok.

<img width="434" alt="image" src="https://github.com/frameless/strapi/assets/49227194/66e50345-d7fd-48b9-a430-edf0974a899e">

**Comment by Ollie-nl** [comment]
Turks en Tigrinya,  mag ook toegevoegd worden als taal keuzen.

**Comment by JeroenduC** [comment]
Gefixt, afgesloten,
