### ISSUE TITLE
OpenForms embed: Gebruik van responsief uitklapmenu voor formulier voortgang op apparaten met smalle schermen

### ISSUE THREAD

**Issue by Ollie-nl** [frameless/strapi#596]
ls bezoeker die een formulier invult op een apparaat met een smalle container (zoals een mobiele telefoon), wil ik een goed werkend uitklapmenu kunnen gebruiken om mijn voortgang in het formulier te kunnen zien en gemakkelijk te navigeren. Dit menu moet eenvoudig te bedienen zijn, zodat ik zonder frustratie of verwarring door mijn formulierinvulling kan navigeren.

![image](https://github.com/frameless/strapi/assets/48805670/bcc1ab43-e1d1-4c79-b29b-31c5766b2d7d)

**Comment by Ollie-nl** [comment]
Heeft Den Haag hier niet al een oplossing voor klaar liggen? Kunnen we later kijken naar een intergratie van hoofd menu met stappen.

**Comment by bddjong** [comment]
PR hiervoor: https://github.com/nl-design-system/utrecht/pull/2197
