### ISSUE TITLE
Voeg meer talen toe aan de TipTap-taalextensie

### ISSUE THREAD

**Issue by AliKdhim87** [frameless/strapi#598]
**Beschrijven:**

De talen die moeten worden toegevoegd zijn:
- Oekraïens
- ..

We moeten met iemand van Gemeente Utrecht valideren of ze nog andere talen willen toevoegen.

**Comment by JeroenduC** [comment]
Volgens mij mag deze gesloten worden, werkt prima, mooie oplossing om de beheerders de beschikbare talen in telaten stellen!
