### ISSUE TITLE
Verticale uitlijning van formulier binnen embed

### ISSUE THREAD

**Issue by Ollie-nl** [frameless/strapi#611]
Als het formulier niet goed past binnen de beschikbare verticale ruimte, wordt het gecentreerd. Dit is niet wenselijk. Voor bezoekers is het duidelijker als het vanaf de bovenkant uitlijnt.

![image](https://github.com/frameless/strapi/assets/48805670/b6ada521-ffb3-489d-950d-0766ebb0d6e9)

**Comment by Ollie-nl** [comment]
Deze is weer terug helaas.

**Comment by JeroenduC** [comment]
Prioriteit opgehoogd vanwege het feit dat dit er uit ziet alsof er een soort bug in de pagina zit.

**Comment by Ollie-nl** [comment]
Lijkt weer goed uit te lijnen op productie
