### ISSUE TITLE
Verplichte Checkbox geeft geen nuttig Error message

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#643]
**Form:** [Klacht over de gemeente doorgeven](https://pdc.cg-intern.acc.utrecht.nl/nl/products/klacht-over-de-gemeente-doorgeven)

**Form Type:** Aanvraag zonder DigiD

**Probleem:** Als man geen optie selecteer bij de verplichte "Weet u voor welke afdeling de medewerker werkt?" radiogroup, krijgt man als error message: "null is een ongeldige keuze" (zie Afbeelding 1).

**Potentiële oplossing:** Voeg een beschrijving toe van wat de ster/asterisk betekent.

**Extra:**  De asterisk naast sommige van de labels van de Text Areas worden gewoon gelezen als "Star" bij de Screenreader. Dit verklaart niet dat de areas met zulke asterisken verplicht zijn. Alleen wanneer man probeert verder te gaan met de Form en klikt op de button "Volgende", kan man een Error message krijgen. Zelfs dan is de error message van de Checkbox momenteel niet duidelijk genoeg, plus de focus ga niet naar een van de verplichte velden dan nog moeten ingevuld worden.

**Gerelateerde afbeelding:**
![Screenshot 2024-04-17 at 17 51 13](https://github.com/frameless/strapi/assets/11764984/6917460f-5010-43f2-8011-c0786ccf9f27)

**WCAG Succes Criteria:**
1.3.1
3.3.2
3.3.1

**Comment by LaurensBurger** [comment]
seems this component has the defaultValue set to: "null", insted of null.

**Comment by AliKdhim87** [comment]
We hebben de openForms bijgewerkt naar versie 2.6.7. Deze issue is opgelost in de nieuwe versie.
