### ISSUE TITLE
Onnodige "arialabeledby" -label + aria-live

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#689]
**Pagina:** [PDC Online Loket Homepagina](https://pdc.cg-intern.acc.utrecht.nl/nl)

**Probleem:** De Searchbar heeft een aria-label en een arialabeledby label (downshift-18-label).  

**Potentiële oplossing:** 
Alleen de aria-label is genoeg om te hebben.

**Extra:** Voeg toe aria-live="polite" zodat de Screenreader gebruiker updates in een beter tempo kan ontvangen (van de item suggesties).

**Gerelateerde afbeelding:**
![Screenshot 2024-04-30 at 11 16 10](https://github.com/frameless/strapi/assets/11764984/86e87f96-5666-4659-a885-1749727b5e74)

**Comment by AliKdhim87** [comment]
Ik heb de zoekbalk aangepast zodat alleen het `aria-labelledby` attribuut behouden blijft. Dit zorgt voor een duidelijke koppeling met het label, wat de toegankelijkheid verbetert voor gebruikers van assistive technologies.

Op basis van de implementatie van de zoekbalk lijkt het niet noodzakelijk om het `aria-live="polite"` attribuut toe te voegen. Het `aria-live` attribuut wordt doorgaans gebruikt om assistive technologies te informeren dat de inhoud binnen een element dynamisch kan veranderen en aan de gebruiker moet worden aangekondigd.

In ons geval lijkt de autocomplete-functionaliteit al goed gestructureerd met passende rollen en attributen, zoals `role="listbox", role="option"`, en `aria-selected`, die voldoende informatie bieden aan assistive technologies over de dynamische wijzigingen in de autocomplete-lijst.

**Comment by savitris** [comment]
@AliKdhim87 
De **aria-labelledby="downshift-382-label"** wordt niet gelezen. Waar komt de waarde **downshift-382-label** vandaan?
Op dit moment, ook al is er een aria-labelledby, wordt er nog steeds van uitgegaan dat de component geen toegankelijke tekst (Accessible Name) bevat.

**Comment by Robbert** [comment]
Gebruik liever `aria-labelledby` dan `aria-label`, voor betere Google Translate support.

**Comment by AliKdhim87** [comment]
@savitris Met betrekking tot het lezen van de aria-labelledby="downshift-382-label" attribuut, welke browser heb jij gebruikt? De waarde van de aria-labelledby wordt automatisch gegenereerd door het [downshift-pakket](https://www.downshift-js.com/use-combobox). Als je de Safari-browser gebruikt, lijkt het erop dat deze een bug heeft: https://github.com/downshift-js/downshift/issues/1539

**Comment by AliKdhim87** [comment]
Het lijkt erop dat het een probleem is met Safari.

- https://github.com/downshift-js/downshift/issues/1181
- https://forums.developer.apple.com/forums/thread/706788

**Comment by savitris** [comment]
> @savitris Met betrekking tot het lezen van de aria-labelledby="downshift-382-label" attribuut, welke browser heb jij gebruikt? De waarde van de aria-labelledby wordt automatisch gegenereerd door het [downshift-pakket](https://www.downshift-js.com/use-combobox). Als je de Safari-browser gebruikt, lijkt het erop dat deze een bug heeft: [downshift-js/downshift#1539](https://github.com/downshift-js/downshift/issues/1539)

@AliKdhim87 Helaas zie ik het probleem ook op Chrome en Edge.
