### ISSUE TITLE
"Rijbewijs aanvragen of verlengen" webpagina toont geen inhoud + Leeg Heading

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#690]
**Pagina:** [Rijbewijs aanvragen of verlengen](https://loket.digitaal.utrecht.nl/nl/products/rijbewijs-aanvragen-verlengen)

**Probleem:** Momenteel, de "Rijbewijs aanvragen of verlengen" webpagina toont geen inhoud. Er wordt geen 404-pagina weergegeven (zie Afbeelding 1).

**Extra:**  De Heading 1 heeft geen toegankelijk tekst (zie Afbeeldingen 2 en 3)

**Gerelateerde afbeelding:**
Afbeelding 1
![Screenshot 2024-04-30 at 12 23 04](https://github.com/frameless/strapi/assets/11764984/da56725e-6880-4286-b7ba-850bca3cf266)
---
Afbeelding 2
![Screenshot 2024-04-30 at 12 21 27](https://github.com/frameless/strapi/assets/11764984/8ca119b0-18a9-46fb-a103-d3927c63062b)
---
Afbeelding 3
![Screenshot 2024-04-30 at 12 22 36](https://github.com/frameless/strapi/assets/11764984/521c7210-712c-4ab9-ac73-d50e9c24db58)

**Comment by AliKdhim87** [comment]
Dit probleem is opgelost door voeging content to the 404 pagina vanuit Strapi
