### ISSUE TITLE
DigiD icon heeft geen label + Link in het Engels mist lang attribute

### ISSUE THREAD

**Issue by savitris** [frameless/strapi#691]
**Pagina:** [Verhuizing doorgeven](https://loket.digitaal.utrecht.nl/nl/products/verhuizing-doorgeven)

**Probleem:** De DigiD logo Icon heeft geen label (titel). Dit betekent dat Screenreader gebruikers niet weten waar het pictogram naar verwijst.

**Potentiële oplossing:** Geef de DigiD logo Icon een label OF een role="presentation"

**Extra:** 

- De "Read this information in English" link op de pagina heeft geen lang="en" attribute(zie Afbeelding 2)

- Zou het beter zijn als de tekst in de knop iets meer beschrijvend zou zijn, zoals "Geef verhuizing door met DigiD"?

**Gerelateerde afbeelding:**

Afbeelding 1
![Screenshot 2024-04-30 at 12 37 20](https://github.com/frameless/strapi/assets/11764984/be44a127-095a-4cc2-9d60-2231ae12d3cc)
---
Afbeelding 2
![Screenshot 2024-04-30 at 12 40 28](https://github.com/frameless/strapi/assets/11764984/35ec6fde-0d8d-4b11-b6f6-512722236fab)

**WCAG Succes Criteria:**
1.1.1
2.4.4
3.1.1

**Comment by Robbert** [comment]
- [ ] `role="presentation` toevoegen
- [ ] instructie in Strapi toevoegen voor redactie dat "DigiD" in de heading of de button tekst genoemd moet worden
