### ISSUE TITLE
Feedback popup Strapi

### ISSUE THREAD

**Issue by Ollie-nl** [frameless/strapi#704]
Als redacteur wil in niet steeds weer de feedback popup zien van Strapi.
De feedback popup blijft terug komen in de back-end van Strapi.
Deze staat in de weg, kan dit uitgezet worden?

![image](https://github.com/frameless/strapi/assets/48805670/0fa5c6a6-dad1-43d2-a65d-f7ba3c56467c)

**Comment by JeroenduC** [comment]
Ook bij het invullen van de feedback, komt hij toch steeds terug :(
