### ISSUE TITLE
In het gebruikersoverzicht werkt het pijltje niet om naar de volgende pagina te gaan. Als ik de weergave instel op ‘100’ zie ik wel alle gebruikers.  

### ISSUE THREAD

**Issue by JeroenduC** [frameless/strapi#715]
In het gebruikersoverzicht werkt het pijltje niet om naar de volgende pagina te gaan. Als ik de weergave instel op ‘100’ zie ik wel alle gebruikers (meer dan 10).  

https://pdc-api.cg-intern.utrecht.nl/admin/settings/users?pageSize=10&page=1&sort=firstname

<img width="1766" alt="image" src="https://github.com/frameless/strapi/assets/49227194/6a7b63fd-908b-4bd2-bea8-0e2ec4826df7">

**Comment by bddjong** [comment]
https://github.com/strapi/strapi/issues/19158

**Comment by Yolijn** [comment]
Oplossing is (hopelijk) om naar de latest stable version van Strapi 4 te upgraden. 
We moeten wel goed testen of alles daarna nog werkt zoals we verwachten, zeker met de uitbreidingen die we hebben gedaan.
