### ISSUE TITLE
Table templates toevoegen aan TipTap

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#741]

**Comment by AliKdhim87** [comment]
**Hier zijn alle pagina's die van tabellen gebruik maken.** :

- https://vth-programma-verslag.digitaal.utrecht.nl/nl/vth-in-cijfers
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/veilig-fietsen
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/nachtelijke-inzet
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/wijkboa-s
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/verkoop-gestolen-spullen
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/controles-ondermijning
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/evenementen
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/speelautomaten
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/coffeeshops
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/horecacontroles
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/achtergelaten-kliko-s
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/afval-naast-containers
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/hondenoverlast
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/theme/huisvesting-de-cijfers
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/slopen
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/theme/controle-wabo-bouwprojecten-tot-2024
- https://vth-programma-verslag.digitaal.utrecht.nl/nl/article/meldingen-en-controles-gebouwen

Gebaseerd op de bovenstaande pagina's zijn de huidige TipTap-tabletemplates volgens mij voldoende. Wat denk jij, @Robbert ?
