### ISSUE TITLE
Margin toevoegen met de nieuwe rich-text component

### ISSUE THREAD

**Issue by AliKdhim87** [frameless/strapi#793]
**Beschrijving:**
In de accordion klopt de spacing niet met de Figma van Utrecht (@AliKdhim87 kun je hier een link naar die Figma frame toevoegen?)

Door spacing toe te voegen met de rich-text component wordt dat misschien al opgelost. 

- [x] Voeg rich-text toe
- [ ] Test of de accordion nu klopt met Figma
- [x] Maak notities van de verschillen die je nog ziet in een comment in dit issue
- [ ] Laat oplossing door Utrecht reviewen

**Comment by AliKdhim87** [comment]
[Figma link](https://www.figma.com/design/J8GosPQdIRzYgXiwB79gks/Formulieren-prototypes-(openForms)?node-id=1080-2308&t=MSGriyIVQtAdVuwm-0)

**Comment by scar055** [comment]
de content in de accordions worden nu goed uit gelijned 

![Image](https://github.com/user-attachments/assets/87bf61aa-5d71-44e9-858c-3481c3a88791)

nu alleen de gap tussen de uitklap button en de accordion content weg halen

**Comment by scar055** [comment]
utrecht vth staat de accordion goed uitgelijned

![Image](https://github.com/user-attachments/assets/1927bbde-e4ec-4215-9496-fb3aef1bcb41)

op de vth is ook de gap tussen de button en de content.

En in het storybook is het ook het zelfde.

**Comment by scar055** [comment]
deze issue kan ik verder werken als deze issue klaar is https://github.com/orgs/frameless/projects/45/views/8?pane=issue&itemId=75023906
