### ISSUE TITLE
Overige Objecten API spike

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#907]
## Context

- [vac-schema.json](https://github.com/user-attachments/files/17187565/vac-schema.json)
- [kennisartikel-schema.json](https://github.com/user-attachments/files/17187568/kennisartikel-schema.json)
- [VNG Realisatie Objecten API](https://github.com/VNG-Realisatie/objecten-api)

## Acceptatie-criteria

- Er is een Node.js server met een REST API die de Overige Object API implementeert en de bovenstaande info teruggeeft
- De REST API is gegenereerd op basis van een Open API specificatie file

# Stories bij deze Spike

- [x] #914 
- [x] #915 
- [x] #916 
- [x] #917 
- [x] #918 
- [x] #920 
- [x] #921
- [x] #923 
- [ ] #919

**Comment by Yolijn** [comment]
# Plan van aanpak
1. Rest API met hardcoded JSON
2. Valideren of uitkomst is wat is verwacht
3. Koppelen aan Strapi data

**Comment by Yolijn** [comment]
# Refinement 30 september

## Aanwezig
Bart Warmenhoven, Laurens Hop, Charlotte Lubongan, Ralf Steenbeek (redacteur kennisbank en online loket), Jeroen du Chatinier, Pieter Valkenburg en  Robbert, Yolijn en Ali van Frameless

---

Digitaal Loket - Product Diensten Catalogus, kennisartikelen toevoegen / samenvoegen. 

Eerste applicatie voor kennisartikel is voor KISS.

Nog een uitbreiding is dan VAC's, daar moet beperkt gebruik van gemaakt worden, alleen als kennisartikelen geen uitkomst brengen.

Bestaande VAC informatie die niet gerelateerd is aan een product.

Informatie transparant conform Common Ground met abonnement, daarvoor Overige Objecten API

---

Welk contentblok hoort bij het kennisartikel, welk contentblok hoort bij de product dienstencatalogus. Als je toch van een veld kan aangeven of het wel/niet bij een product hoort of kennisartikel.

---

Aansluiting op KISS overige objecten API meest prangend. Wat er intern in het datamodel gebeurt kunnen we mee shuffle-en. Wat we dachten is eerst richten koppeling KISS met Overige Objecten API.

Firewall verbindingen, etc. gelijk achter komen. Dan weten we zo snel mogelijk.

---

Kennisartikel informatie

---

OTA straat inrichten voor KISS, OTA straat van Strapi moet daarop aangesloten worden. Vanuit Utrecht eerste sprint.

Liefst modern met JWT-token met oAuth vanuit Azure.

---

ICATT direct schakelen, Utrecht meer regie ipv vertragende factor.

Ergens iets met ICAT inplannen. Utrecht gaat dat voorstellen, Charlotte organiseert dit als vervanger van Justin

---

**Comment by Robbert** [comment]
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/maykinmedia/objects-api/master/src/objects/api/v2/openapi.yaml

https://raw.githubusercontent.com/maykinmedia/objects-api/master/src/objects/api/v2/openapi.yaml

**Comment by Yolijn** [comment]
# Stories bij deze Spike
- #914 
- #915 
- #916 
- #917 
- #918 
- #919 
- #920 
- #921
