### ISSUE TITLE
Voeg ontbrekende velden toe aan Strapi ter ondersteuning van Kennisartikel informatiemodel

### ISSUE THREAD

**Issue by Yolijn** [frameless/strapi#927]
Er is een Overige Objecten API voor Kennisartikelen beschikbaar gemaakt, maar deze heeft nog niet een goede koppeling voor alle velden in Strapi.

- [x] #935
- [x] #932
- [x] #933
- [x] #934
- [ ] Valideer met data analist en business analisten dat de koppeling van informatie klopt
- [ ] Valideer met redactie dat de koppeling van informatie klopt

**Comment by AliKdhim87** [comment]
**Lijst van ontbrekende informatie die toegevoegd moet worden aan producten in Strapi om te voldoen aan het kennisartikel informatiemodel**
- doelgroep
- productAanwezig
- productValtOnder
- afdelingen
   - afdelingId
   - afdelingnaam
   
- verantwoordelijkeOrganisatie
   - owmsIdentifier
   - owmsPrefLabel
   - owmsEndDate
   
- upnUri
